disabled_rules: # rule identifiers to exclude from running
- identifier_name
- multiple_closures_with_trailing_closure
- trailing_whitespace
- force_try
- force_cast
- line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
